### PR TITLE
Windows/VSC dev, dependencies, and lint configs

### PR DESCRIPTION
**Pull request by Unnoen**
* Bump all dependencies
* Generate .lock file for Windows development
* Use GitHub for discordrb gem
+ Add debase and ruby-debug-ide for debugging
+ VSCode workspace configs
+ Lint configs

I've made the lint configs less annoying and have picked 2.7 for the target version. Do you want to commit to using 2.5?

### CODE REVIEW

**Comment by tr4wzified** [comment]
Why would we want to pull discordrb from GitHub instead of the normal gems repository?

I've edited some stuff so those dev gems don't get installed on the production environment. Ruby 2.5 won't work because I use .filter in the showlisteners command, 2.5.5 is the minimum you can use to keep the bot fully functional but I want to give 3.0 a shot as it's the latest and the fastest.

Also edited some of the Rubocop stuff you turned off, some of the warnings I do still want to change, like the missing documentation. That's a good validation check in my opinion.

**Comment by Unnoen** [comment]
I'm not sure about the RubyGems version, I saw that it was no longer updated so I switched it to the GitHub repo so we can be sure it's the latest version.

The Rubocop rules I changed are enabled by default, so we can just remove them from the list rather than setting them to true.

The .lock file should always be checked in as it contains the exact versions and dependencies installed, https://bundler.io/v2.2/rationale.html#checking-your-code-into-version-control

**Comment by tr4wzified** [comment]
Great, I've asked on the discordrb discord (or well, the one for all the discord libraries) about the mismatch - did find some messages saying 3.4.1 and 3.4.2 had some borked methods so probably gonna pass on that.

**Comment by tr4wzified** [comment]
Official response
image

**Pull request merged**
